apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-site-deployment
  namespace: test
  labels:
    app: customer-site
spec:
  selector:
    matchLabels:
      app: customer-site
  template:
    metadata:
      labels:
        app: customer-site
    spec:
      containers:
      - name: myapp
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
