apiVersion: v1
kind: Service
metadata:
  name: customer-site-service
  namespace: customer-site
spec:
  selector:
    app: customer-site
  ports:
  - port: 50009
    targetPort: 5000
  type: NodePort
